# Generated by Django 5.0.3 on 2024-04-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
