# Generated by Django 5.0.3 on 2024-04-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=True, max_length=11, unique=True, verbose_name='شماره همراه'),
        ),
    ]
