# Generated by Django 5.0.3 on 2024-09-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order',
            field=models.IntegerField(default=0),
        ),
    ]
