# Generated by Django 5.0.3 on 2024-09-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_total_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_order',
            new_name='total_price',
        ),
    ]
