# Generated by Django 5.0.3 on 2024-09-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_orderitem_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('discount', models.SmallIntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
